### ISSUE TITLE
what are the labels?

### ISSUE THREAD

**Issue by shirellm** [UMich-CURLY/deep-contact-estimator#2]
Hello there, may I ask what are the labels meanings? I see there are values of 0, 6 and 9 (in the array inside label.npy files). what are those numbers represent?
and also if you can please explain what are the network outputs? i.e. what is the form of S (contact state)

**Comment by tzuyuan** [comment]
Hello!

The labels are binary contact values converted into decimal integers. For our quadruped robot, we define our binary contact state as $C = [c_{RF}, c_{LF}, c_{RH}, c_{LH}], c_l \in {0,1}$, with $1$ denoting a contact and $0$ denoting no contact. 

The contact state $S$ is a result of converting the binary contact vector $C$ into an integer. For example, when only the left front leg and left hind leg are having contact, we have $C = [0,1,0,1]$, and the corresponding $S$ is 
$1*(2^2)+1*(2^0)=5$. The labels in `label.npy` are this $S$ value. So does the network output. 

You can find a more detailed description in our paper: https://proceedings.mlr.press/v164/lin22b/lin22b.pdf.
