### ISSUE TITLE
Question on units for foot positions/velocities in contact datasets

### ISSUE THREAD

**Issue by DanielChaseButterfield** [UMich-CURLY/deep-contact-estimator#4]
Your paper mentions the following units and frames for your dataset values:
![image](https://github.com/user-attachments/assets/b81d9ab2-9733-4f96-9c91-d3ac8a7613be)

I noticed that the units for foot position & velocity is not specified. Would these be in meters & meters/sec respectively, relative to the robot's hip frame?

**Comment by tzuyuan** [comment]
Hi Daniel, 

Yes, they're in meters and meters/sec, respectively.
